# -*- coding: utf-8 -*-
"""
Builds the word lists the app studies from, straight from the official source.

    py -m pip install pypdf        (once)
    py scripts/build_data.py

Where the data comes from
  1. The official 2025 HSK syllabus PDF (新版HSK考试大纲), published by
     Chinese Testing International. It decides which level every word is in
     and how it is officially read.
  2. CC-CEDICT, the free Chinese-English dictionary. Used only for meanings,
     and always the entry matching the official reading, so 便宜 gets
     "cheap" (piányi) and not "convenient" (biànyí).
  3. A frequency-ordered copy of the syllabus, used only to put the most
     common words first inside each level.

Downloads are cached as data/_* files, which are not kept in git.
"""
import bz2, collections, io, itertools, json, os, re, unicodedata, urllib.parse, urllib.request, zipfile

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data")

SYLLABUS_URL = ("https://hsk.cn-bj.ufileos.com/3.0/"
                + urllib.parse.quote("新版HSK考试大纲（词汇、汉字、语法）.pdf"))
CEDICT_URL = "https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip"
FREQ_URL = ("https://raw.githubusercontent.com/krmanik/HSK-3.0/main/"
            + urllib.parse.quote("New HSK (2025)/hsk_all_words.json"))

# Example sentences: Tatoeba, human-written and free (CC BY 2.0 FR).
TATOEBA = "https://downloads.tatoeba.org/exports/per_language/"
CMN_URL   = TATOEBA + "cmn/cmn_sentences.tsv.bz2"      # id, lang, Chinese text
LINKS_URL = TATOEBA + "cmn/cmn-eng_links.tsv.bz2"      # Chinese id -> English id
ENG_URL   = TATOEBA + "eng/eng_sentences.tsv.bz2"      # id, lang, English text

CREDIT = ("Sentences from Tatoeba (CC BY 2.0 FR). "
          "Pinyin for them is generated by scripts/build_data.py, not by Tatoeba.")

LEVELS = ["1", "2", "3", "4", "5", "6", "7-9"]          # saved as hsk1 ... hsk7
EXPECTED = {"1": 300, "2": 200, "3": 500, "4": 1000, "5": 1600, "6": 1800, "7-9": 5600}

# The only glosses written by hand: words whose official reading has no
# matching dictionary entry at all.
MANUAL = {
    "嗯":       ["mm-hmm; OK (agreeing or acknowledging)"],
    "精彩纷呈": ["full of brilliant moments", "a dazzling array of highlights"],
}

# The PDF's text layer loses the brackets around optional parts: the page
# prints 没（有） but the text reads 没有, and 有（一）点儿 comes out as 有点儿.
# Checked against two independent transcriptions of the printed page.
# The script stops if these ever stop matching the PDF.
BRACKET_FIXES = {
    ("1", "没有"):   ("没（有）",     "méi(yǒu)"),
    ("1", "有点儿"): ("有（一）点儿", "yǒu(yì)diǎnr"),
    ("2", "有时"):   ("有时（候）",   "yǒushí(hou)"),
    ("4", "差点儿"): ("差（一）点儿", "chà(yì)diǎnr"),
    ("5", "要不"):   ("要不（然）",   "yàobù(rán)"),
    ("6", "凡是"):   ("凡（是）",     "fán(shì)"),
}

# How to read a character when it stands on its own in a sentence.
# Most characters are decided by a vote (see pinyin_table). These are the ones
# the vote gets wrong, because how often a reading appears in DICTIONARY WORDS
# is not how often it appears in ACTUAL SENTENCES.
CHAR_DEFAULT = {
    "的": "de5",    # the vote says dì, from 目的, 的确
    "了": "le5",    # the vote says liǎo, from 了解
    "着": "zhe5",   # the vote says zhuó, from 着手
    "过": "guo4",
    "得": "de5",    # the vote says dé, from 得到
    "地": "de5",    # the vote says dì, from 地方 - but bare 地 is usually the adverb particle
    "都": "dou1",   # the vote says dū, from 首都
    "还": "hai2",   # the vote says huán, from 还给
    "为": "wei4",
    "累": "lei4",
    "差": "cha4",
    "干": "gan4",
    "吧": "ba5",
    "吗": "ma5",
    "呢": "ne5",
    "啊": "a5",
    "么": "me5",
    "只": "zhi3",
    "少": "shao3",
    "给": "gei3",
    "没": "mei2",
    "谁": "shei2",
}

# Sentence pinyin you have corrected by hand, keyed by Tatoeba sentence id.
# The build stops if one of these no longer matches a chosen sentence, so a
# correction can never quietly stop being applied.
SENTENCE_PINYIN_FIXES = {}


def fetch(url, name):
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        print("downloading", name, "...")
        req = urllib.request.Request(url, headers={"User-Agent": "hanzi-build"})
        with urllib.request.urlopen(req, timeout=300) as r:
            body = r.read()
        if name.endswith(".txt"):                      # CEDICT arrives zipped
            z = zipfile.ZipFile(io.BytesIO(body))
            body = z.read(z.namelist()[0])
        elif name.endswith(".tsv"):                    # Tatoeba arrives bzipped
            body = bz2.decompress(body)
        with open(path, "wb") as f:
            f.write(body)
    return path


# ---------------------------------------------------------------- pinyin ---

MARKS = {"a": "āáǎà", "e": "ēéěè", "i": "īíǐì", "o": "ōóǒò", "u": "ūúǔù", "ü": "ǖǘǚǜ"}

def mark(syl):
    """CEDICT writes "hao3"; the syllabus writes "hǎo". Convert the first to the second."""
    syl = syl.lower().replace("u:", "ü")
    m = re.match(r"^([a-zü]+?)([1-5])$", syl)
    if not m:
        return syl
    s, tone = m.group(1), int(m.group(2))
    if tone == 5:                                        # neutral tone: no mark
        return s
    for v in ("a", "e"):                                 # standard placement rules
        if v in s:
            return s.replace(v, MARKS[v][tone - 1], 1)
    if "ou" in s:
        return s.replace("o", MARKS["o"][tone - 1], 1)
    for i in range(len(s) - 1, -1, -1):
        if s[i] in MARKS:
            return s[:i] + MARKS[s[i]][tone - 1] + s[i + 1:]
    return s

def norm(p):
    """Comparable form: lower case, no spaces or apostrophes."""
    return re.sub(r"[\s'’ʼ·∥\-]", "", unicodedata.normalize("NFC", p.lower()))

def toneless(p):
    return "".join(c for c in unicodedata.normalize("NFD", p)
                   if unicodedata.category(c) != "Mn")

def spellings(word, syllables):
    """Every way the syllabus might spell a CEDICT entry. The syllabus marks
    the tone changes of 一 and 不 (yíbàn, búcuò); CEDICT never does."""
    options = []
    for i, s in enumerate(syllables):
        ch = word[i] if len(word) == len(syllables) else ""
        base = re.sub(r"\d", "", s).lower()
        if ch == "一" and base == "yi":
            options.append([mark(base + t) for t in "124"])
        elif ch == "不" and base == "bu":
            options.append([mark(base + t) for t in "24"])
        else:
            options.append([mark(s)])
    return {norm("".join(combo)) for combo in itertools.product(*options)}


# -------------------------------------------------------------- syllabus ---

def read_syllabus():
    from pypdf import PdfReader
    pdf = fetch(SYLLABUS_URL, "_hsk2025_syllabus.pdf")

    lv = r"(?:7-9|\d)"
    pos = r"[名动形副代数量介连助叹拟声前后缀、（）()]+"
    row = re.compile(rf"^(\d+)\s+({lv}(?:（{lv}）)*)\s+(\S+)\s+(.*?)\s*({pos})?\s*$")

    rows = {}
    for page in PdfReader(pdf).pages:
        for line in (page.extract_text() or "").splitlines():
            m = row.match(line.strip())
            if not m or int(m.group(1)) in rows:
                continue
            n = int(m.group(1))
            rows[n] = {
                "n":     n,
                "level": re.match(lv, m.group(2)).group(),   # "1（4）" -> "1"
                "word":  re.sub(r"\d+$", "", m.group(3)),     # "点1" -> "点"
                # The part-of-speech column can contain a space ("名、 形"),
                # so cut the pinyin at the first Chinese character.
                "py":    re.sub(r"\s*(?:" + CJK + r"|[、（]).*$", "",
                                re.sub(r"\s+", " ", m.group(4))).strip(),
            }
            if len(rows) == 11000:              # later tables restart numbering
                break
        if len(rows) == 11000:
            break

    fixed = 0
    for r in rows.values():
        fix = BRACKET_FIXES.get((r["level"], r["word"]))
        if fix:
            r["word"], r["py"] = fix
            fixed += 1
    assert fixed == len(BRACKET_FIXES), "BRACKET_FIXES no longer match the PDF"

    # Guard against a bad parse silently producing a short word list.
    counts = collections.Counter(r["level"] for r in rows.values())
    assert sorted(rows) == list(range(1, 11001)), "syllabus rows missing"
    assert dict(counts) == EXPECTED, f"level counts off: {dict(counts)}"
    return [rows[n] for n in sorted(rows)]


# ------------------------------------------------------------ dictionary ---

# Dictionary notes that are not meanings. Kept narrow on purpose: "surname
# Zhang" is skipped, but "surname and given name" (姓名) is a real meaning.
CJK = r"[㐀-鿿]"
SKIP = re.compile(rf"^(surname [A-Z][a-z]*(\s|$)|(old |archaic )?variant of|erhua variant of|"
                  rf"also written|[\w. ]*\bpr\.|CL:|see (also )?{CJK}|"
                  rf"used in {CJK}|used in transliteration)")

def load_cedict():
    ced = collections.defaultdict(list)
    with open(fetch(CEDICT_URL, "_cedict.txt"), encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^\S+ (\S+) \[([^\]]*)\] /(.*)/\s*$", line)
            if m:
                ced[m.group(1)].append((m.group(2).split(), m.group(3).split("/")))
    return ced

def clean(entries):
    out = []
    for _, defs in entries:
        for d in defs:
            d = d.strip()
            if not d or SKIP.match(d):
                continue
            # "(CL:个[ge4])", "(Taiwan pr. [...])", "(old pr. [...])": notes, not meaning
            d = re.sub(r"\s*\(CL:[^)]*\)", "", d)
            d = re.sub(r"\s*\([^()]*\bpr\.[^()]*\)", "", d)
            d = re.sub(r"\[[^\]]*\]", "", d)                     # 折[zhe2] -> 折
            d = re.sub(CJK + r"+\|(" + CJK + r"+)", r"\1", d)    # 摺|折 -> 折
            d = re.sub(r"\(\s*\)", "", d).strip()
            if d and d not in out:
                out.append(d)
    return out[:3]

# "variant of 作證|作证[zuo4 zheng4]" or "see 血[xue4]" -> ("作证", "zuo4 zheng4")
POINTER = re.compile(r"^(?:(?:old |archaic |erhua )?variant of|see(?: also)?) "
                     r"(?:[^\s|\[]+\|)?([^\s|\[]+)\[([^\]]+)\]")

def follow(ced, entries, hops=2):
    """Some entries only point elsewhere (辞典: "variant of 词典"). Use the
    meanings of the exact spelling and reading they point to."""
    for _, defs in entries:
        for d in defs:
            m = POINTER.match(d.strip())
            if not m:
                continue
            target, py = m.group(1), m.group(2).lower().split()
            hits = [e for e in ced.get(target, []) if [s.lower() for s in e[0]] == py]
            got = clean(hits) or (follow(ced, hits, hops - 1) if hops > 1 else [])
            if got:
                return got
    return []

def meanings(ced, word, py, other_readings, report):
    if word in MANUAL:
        report["hand-written"].append(word)
        return MANUAL[word]

    py = py.split("/")[0]
    # 没（有） méi(yǒu): try the full form 没有, then the short form 没.
    full  = (re.sub(r"[（）]", "", word), norm(re.sub(r"[()]", "", py)))
    short = (re.sub(r"（.*?）", "", word), norm(re.sub(r"\(.*?\)", "", py)))
    tries = [full] if full == short else [full, short]
    for w, p in list(tries):
        if w.endswith("儿") and len(w) > 1:                       # 口哨儿 -> 口哨
            tries.append((w[:-1], p[:-1] if p.endswith("r") else p))

    for w, p in tries:
        entries = ced.get(w, [])
        if not entries:
            continue
        exact = [e for e in entries if p in spellings(w, e[0])]
        # Same letters, different tone: usually a neutral tone CEDICT leaves
        # out. Never borrow the entry that belongs to another official reading.
        loose = [e for e in entries
                 if toneless(p) == toneless(norm("".join(mark(s) for s in e[0])))
                 and not any(o in spellings(w, e[0]) for o in other_readings)]
        chosen = exact or loose or entries
        # Lower-case reading -> ignore proper-noun entries (surname Zhang, etc.)
        if p == p.lower():
            chosen = [e for e in chosen if not e[0][0][:1].isupper()] or chosen
        defs = clean(chosen)
        if not defs:
            defs = follow(ced, chosen)
            if defs:
                report["via main spelling"].append(word)
        if defs:
            if not exact:
                report["closest reading" if loose else "any reading"].append(f"{word} {py}")
            return defs
    report["no meaning"].append(f"{word} {py}")
    return None


# ------------------------------------------------------ example sentences ---

def traditional_only_chars():
    """Characters that only exist in traditional writing (說, 這, 個, 們).

    Tatoeba mixes both scripts and this app is simplified-only, so any
    sentence containing one of these is thrown away. The set falls out of
    CC-CEDICT: every character in its traditional column that never appears
    in its simplified column."""
    simp, trad = set(), set()
    with open(os.path.join(DATA, "_cedict.txt"), encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            m = re.match(r"^(\S+) (\S+) ", line)
            if m:
                trad.update(m.group(1))
                simp.update(m.group(2))
    return trad - simp


def pinyin_table(ced):
    """word -> numbered syllables, e.g. 学校 -> ["xue2", "xiao4"].

    Single characters are the hard part. CEDICT sorts its entries by pinyin,
    so "the first entry" for 看 is kān, when running text almost always wants
    kàn. Instead we hold a vote: 看 is read kan4 in 148 dictionary words and
    kan1 in 12, so kàn wins. CHAR_DEFAULT above overrides the handful the
    vote still gets wrong."""
    table = {}
    votes = collections.defaultdict(collections.Counter)

    for word, entries in ced.items():
        if len(word) < 2:
            continue
        # Skip proper nouns (capitalised) where there is an alternative, then
        # take the alphabetically first, so the table is identical every run.
        options = [e[0] for e in entries if not e[0][0][:1].isupper()] or [e[0] for e in entries]
        best = sorted(options, key=lambda s: " ".join(s))[0]
        table[word] = best
        if len(word) == len(best):
            for ch, syl in zip(word, best):
                votes[ch][syl.lower()] += 1

    for word, entries in ced.items():
        if len(word) != 1:
            continue
        if word in CHAR_DEFAULT:
            table[word] = [CHAR_DEFAULT[word]]
        elif votes[word]:
            table[word] = [votes[word].most_common(1)[0][0]]
        else:
            table[word] = entries[0][0]
    return table


def segment(text, table):
    """Split a sentence into dictionary words, longest match first.

    This is where most of the work happens: matching 银行 as a word gives
    yínháng rather than yín-xíng, with no special handling needed.
    Returns [chunk, syllables] pairs; syllables is None for anything not in
    the dictionary, such as punctuation."""
    out, i = [], 0
    while i < len(text):
        for size in range(min(8, len(text) - i), 0, -1):
            chunk = text[i:i + size]
            if chunk in table:
                out.append([chunk, list(table[chunk])])
                i += size
                break
        else:
            out.append([text[i], None])
            i += 1
    return out


def sandhi(pieces):
    """The tone changes of 不 and 一: bù becomes bú before a fourth tone, and
    一 becomes yí before a fourth tone, yì before anything else.

    It runs over the whole sentence rather than word by word, because
    一点儿 is matched as a single dictionary word and a word-boundary pass
    would never look inside it. spellings() above lists every spelling the
    syllabus might use; this picks the one that is actually said."""
    flat = []                       # (piece, position in piece, char, syllable)
    for pi, (chunk, syls) in enumerate(pieces):
        if syls and len(syls) == len(chunk):
            for si, (ch, syl) in enumerate(zip(chunk, syls)):
                flat.append((pi, si, ch, syl))

    for n, (pi, si, ch, syl) in enumerate(flat):
        base = re.sub(r"\d", "", syl).lower()
        nxt  = flat[n + 1][3] if n + 1 < len(flat) else ""
        prev = flat[n - 1][2] if n else ""
        if ch == "不" and base == "bu":
            pieces[pi][1][si] = "bu2" if nxt.endswith("4") else "bu4"
        elif ch == "一" and base == "yi":
            if n + 1 == len(flat) or prev == "第" or nxt[:1].isdigit():
                pieces[pi][1][si] = "yi1"          # 十一, 第一
            elif nxt.endswith("4"):
                pieces[pi][1][si] = "yi2"
            else:
                pieces[pi][1][si] = "yi4"
    return pieces


PUNCT = {"。": ".", "，": ",", "？": "?", "！": "!", "：": ":", "；": ";",
         "、": ",", "“": '"', "”": '"', "‘": "'", "’": "'", "…": "...",
         "《": '"', "》": '"', "（": "(", "）": ")"}

CJK_CHAR = re.compile(CJK)


def marked(syllable):
    """Tone marks, keeping the capital on proper nouns: Zhōngguó, Běijīng."""
    out = mark(syllable)
    return out[:1].upper() + out[1:] if syllable[:1].isupper() else out


def sentence_pinyin(text, table, guessed=None):
    """Tone-marked pinyin for a whole sentence.

    Returns (pinyin, syllable count, ok). ok is False when a Chinese
    character is not in the dictionary at all, which means we cannot write
    honest pinyin for the sentence and the caller should skip it."""
    out, syllables, ok, quotes, sentence_start = "", 0, True, 0, True

    for chunk, syls in sandhi(segment(text, table)):
        if syls is None:
            if CJK_CHAR.match(chunk):
                ok = False                          # unknown character
                continue
            piece = PUNCT.get(chunk, chunk)
            out += piece
            quotes += piece.count('"')
            if piece in ".?!":
                sentence_start = True               # capitalise what comes next
            continue

        if len(chunk) == 1 and CJK_CHAR.match(chunk) and guessed is not None:
            guessed[chunk] += 1                     # read alone, not as part of a word

        # A space before each word, except after an opening bracket or quote.
        if out and not out.endswith("(") and not (out.endswith('"') and quotes % 2):
            out += " "

        word = "".join(marked(s) for s in syls)
        out += (word[:1].upper() + word[1:]) if sentence_start else word
        sentence_start = False
        syllables += len(syls)

    return (out.strip(), syllables, ok)


def load_sentences():
    """Tatoeba's Mandarin sentences that have an English translation."""
    links = {}
    with open(fetch(LINKS_URL, "_cmn_eng_links.tsv"), encoding="utf-8") as f:
        for line in f:
            cmn_id, _, eng_id = line.strip().partition("\t")
            if eng_id:
                links.setdefault(cmn_id, eng_id)

    chinese = {}
    with open(fetch(CMN_URL, "_cmn_sentences.tsv"), encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 3 and p[0] in links:
                chinese[p[0]] = p[2]

    wanted = {links[sid] for sid in chinese}
    english = {}
    with open(fetch(ENG_URL, "_eng_sentences.tsv"), encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 3 and p[0] in wanted:
                english[p[0]] = p[2]

    return {sid: (txt, english[links[sid]])
            for sid, txt in chinese.items() if links[sid] in english}


def pick_sentences(words_by_level, sentences, table, report):
    """Choose one example sentence per word: short, simplified, natural, and
    made of words the reader is likely to know."""
    trad_only = traditional_only_chars()
    assert len(trad_only) > 3000, "traditional-only character set looks wrong"

    hsk = {w: lv for lv, words in words_by_level.items() for w in words}
    guessed = collections.Counter()

    usable = {}
    for sid, (txt, eng) in sentences.items():
        chars = CJK_CHAR.sub("", txt)                  # non-Chinese leftovers
        count = len(txt) - len(chars)
        if not 4 <= count <= 20:                       # long enough, not a wall
            continue
        if set(txt) & trad_only or re.search(r"[A-Za-z0-9]", txt):
            continue
        pinyin, syllables, ok = sentence_pinyin(txt, table, guessed)
        if not ok or syllables != count:               # cannot read it honestly
            continue
        tokens = [c for c, _ in segment(txt, table)]
        usable[sid] = (txt, eng, count, pinyin, tokens, set(tokens))

    # Which sentences contain which of our words.
    index = collections.defaultdict(list)
    for sid, (txt, *_rest) in usable.items():
        inside = {txt[i:i + size]
                  for i in range(len(txt)) for size in range(1, 7)
                  if i + size <= len(txt)}
        for w in inside & hsk.keys():
            index[w].append(sid)

    used, picked = collections.Counter(), {}
    for level in sorted(words_by_level):               # common words pick first
        for word in words_by_level[level]:
            best = best_score = None
            for sid in index.get(word, ()):
                txt, eng, count, pinyin, tokens, token_set = usable[sid]
                # The word has to really be in the sentence, not straddle two
                # other words: 上去 must not be taught with 早上|去世. Sitting
                # inside one longer word is fine (星期 within 星期天).
                # A single character must stand alone, so 行 xíng is never
                # really the 行 háng of 银行.
                if len(word) == 1:
                    if word not in token_set:
                        continue
                elif not any(word in token for token in token_set):
                    continue

                score = abs(count - 9)                 # aim for about 9 characters
                for t in tokens:
                    if CJK_CHAR.match(t):
                        at = hsk.get(t)
                        score += 3 if at is None else (1 if at > level else 0)
                if txt[-1] not in "。！？":
                    score += 3
                if not 8 <= len(eng) <= 90:
                    score += 2
                score += 4 * used[sid]                 # spread sentences around

                if best_score is None or (score, int(sid)) < best_score:
                    best, best_score = sid, (score, int(sid))

            if best is None:
                report["no sentence"].append(word)
                continue
            used[best] += 1
            txt, eng, _count, pinyin, *_ = usable[best]
            picked[word] = {"s": txt, "p": pinyin, "e": eng, "i": int(best)}

    report["guessed reading"] = [f"{c}x{n}" for c, n in guessed.most_common(20)]
    return picked


# ----------------------------------------------------------------- build ---

def main():
    rows = read_syllabus()
    ced = load_cedict()

    # One card per written word. A word listed several times (new senses at
    # higher levels, or a second reading) becomes one card at its first level.
    cards = {}
    for r in rows:
        lv = LEVELS.index(r["level"]) + 1
        card = cards.setdefault(r["word"], {"level": lv, "readings": {}})
        card["level"] = min(card["level"], lv)
        key = norm(r["py"])
        reading = card["readings"].setdefault(key, {"p": r["py"], "level": lv, "n": r["n"]})
        reading["level"] = min(reading["level"], lv)

    # Frequency order inside each level.
    with open(fetch(FREQ_URL, "_hsk2025_freq.json"), encoding="utf-8") as f:
        freq = json.load(f)
    rank = {}
    for i, lvkey in enumerate(LEVELS):
        for pos, w in enumerate(freq.get("hsk" + lvkey, [])):
            rank.setdefault((i + 1, re.sub(r"\d+$", "", w)), pos)

    report = collections.defaultdict(list)
    levels = {n: [] for n in range(1, 8)}
    for word, card in cards.items():
        readings = sorted(card["readings"].values(), key=lambda r: (r["level"], r["n"]))
        all_keys = [norm(r["p"].split("/")[0]) for r in readings]
        out = []
        for i, r in enumerate(readings):
            others = all_keys[:i] + all_keys[i + 1:]
            p = r["p"].replace("/", " / ")                        # shéi/shuí
            out.append({"p": p, "m": meanings(ced, word, r["p"], others, report)})
        entry = {"s": word, "p": out[0]["p"], "m": out[0]["m"]}
        if len(out) > 1:
            entry["a"] = out[1:]
            report["several readings"].append(word)
        first_row = min(r["n"] for r in readings)
        levels[card["level"]].append((rank.get((card["level"], word), 10**6 + first_row), entry))

    # Stop before writing anything, and list every problem at once.
    if report["no meaning"]:
        raise SystemExit("No meaning found for: " + ", ".join(report["no meaning"])
                         + "\nAdd them to MANUAL. Nothing was written.")

    for items in levels.values():
        items.sort(key=lambda x: x[0])                 # commonest word first
    words_by_level = {n: [e["s"] for _, e in items] for n, items in levels.items()}

    print("choosing example sentences...")
    examples = pick_sentences(words_by_level, load_sentences(), pinyin_table(ced), report)

    applied = 0
    for ex in examples.values():
        if ex["i"] in SENTENCE_PINYIN_FIXES:
            ex["p"] = SENTENCE_PINYIN_FIXES[ex["i"]]
            applied += 1
    assert applied == len(SENTENCE_PINYIN_FIXES), "SENTENCE_PINYIN_FIXES no longer match"

    total = sum(len(w) for w in words_by_level.values())
    assert len(examples) > 0.55 * total, f"sentence coverage collapsed: {len(examples)}/{total}"

    index = []
    for n, items in levels.items():
        words = [e for _, e in items]
        path = os.path.join(DATA, f"hsk{n}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(words, f, ensure_ascii=False, separators=(",", ":"))

        # Sentences live in their own file so the word list stays small and
        # the first card appears without waiting for them.
        ex = {"_credit": CREDIT}
        for e in words:
            if e["s"] in examples:
                ex[e["s"]] = examples[e["s"]]
        ex_path = os.path.join(DATA, f"ex{n}.json")
        with open(ex_path, "w", encoding="utf-8") as f:
            json.dump(ex, f, ensure_ascii=False, separators=(",", ":"))

        index.append({"level": n, "count": len(words)})
        have = len(ex) - 1
        print(f"hsk{n}.json {len(words):>5} cards {os.path.getsize(path) / 1024:>5.0f} KB"
              f"   ex{n}.json {have:>5} sentences ({have / len(words) * 100:4.1f}%)"
              f" {os.path.getsize(ex_path) / 1024:>5.0f} KB")

    with open(os.path.join(DATA, "index.json"), "w", encoding="utf-8") as f:
        json.dump(index, f)

    print("total:", sum(i["count"] for i in index), "cards from", len(rows), "syllabus rows")
    print("examples:", len(examples), f"({len(examples) / total * 100:.1f}%)")
    for k in ("several readings", "closest reading", "any reading", "via main spelling",
              "hand-written", "no sentence", "guessed reading"):
        v = report[k]
        print(f"{k}: {len(v)}" + (f"  e.g. {', '.join(v[:12])}" if v else ""))

    # You speak Mandarin, so you are the only real test of the tones.
    step = max(1, len(examples) // 20)
    print("\nsample sentences - check the tones:")
    for w in sorted(examples)[::step][:20]:
        e = examples[w]
        print(f"  {w:8} {e['s']:24} {e['p']}   ({e['e']})")


if __name__ == "__main__":
    main()
